# -*- coding: utf-8 -*-
"""trainingVGG16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SPcqMhE6C-f8EvsGfeTw6dT2aIFdv9Wy
"""

#The model is compiled with Adam optimization and accuracy metric.
  model.compile(
      optimizer='adam',
      loss=losses.sparse_categorical_crossentropy,
      metrics=['accuracy']
  )
  return model

#Define and Train the Model
model = my_model()

#Fitting (Training) the Model
history = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=20
)