# -*- coding: utf-8 -*-
"""VGG16model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/165dXerpa8HHso0UzlUqQOWqF9RSpyi-p
"""

#Allows defining the input type to be used in the model
input_shape = (224, 224)
IMG_SIZE = input_shape + (3,)

# Function to create and compile the model
def my_model():
  #It takes VGG16 pre-trained with ImageNet.Top layers are excluded.
  network=applications.VGG16(input_shape=IMG_SIZE,
                             include_top=False,
                             weights='imagenet')


  #VGG16 weights are not updated during training.Several fully-connected layers are added on top of it.
  network.trainable=False
  model=models.Sequential([
      network,
      layers.Flatten(),
      layers.Dense(128,activation='relu'),
      layers.Dense(64,activation='relu'),
      layers.Dense(32,activation='relu'),
      layers.Dense(5,activation='softmax')
  ])